/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyButton {
        /**
          * the background color when type is "contained", the foreground color when type is "outlined"
         */
        "color"?: 'primary' | 'secondary';
        /**
          * indicating disabled button
         */
        "disabled"?: boolean;
        /**
          * The size of the button
         */
        "size"?: 'big' | 'regular' | 'small';
        /**
          * the type of the button
         */
        "type"?: 'contained' | 'outlined';
        /**
          * The width of the button
         */
        "width"?: 'wide' | 'medium' | 'narrow';
    }
}
declare global {
    interface HTMLMyButtonElement extends Components.MyButton, HTMLStencilElement {
    }
    var HTMLMyButtonElement: {
        prototype: HTMLMyButtonElement;
        new (): HTMLMyButtonElement;
    };
    interface HTMLElementTagNameMap {
        "my-button": HTMLMyButtonElement;
    }
}
declare namespace LocalJSX {
    interface MyButton {
        /**
          * the background color when type is "contained", the foreground color when type is "outlined"
         */
        "color"?: 'primary' | 'secondary';
        /**
          * indicating disabled button
         */
        "disabled"?: boolean;
        /**
          * The size of the button
         */
        "size"?: 'big' | 'regular' | 'small';
        /**
          * the type of the button
         */
        "type"?: 'contained' | 'outlined';
        /**
          * The width of the button
         */
        "width"?: 'wide' | 'medium' | 'narrow';
    }
    interface IntrinsicElements {
        "my-button": MyButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-button": LocalJSX.MyButton & JSXBase.HTMLAttributes<HTMLMyButtonElement>;
        }
    }
}
